import type { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'
import { Poppins } from 'next/font/google'

import SessionProvider from '@/app/context/session-provider'

import './globals.css'


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: {
    template: '%s | Temu Kampus',
    absolute: 'Temu Kampus'
  },
  description: 'Generated by create next app'
}

type RootLayoutProps = Readonly<{
  children: ReactNode
}>

export default function RootLayout({
  children
}: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toaster position="top-center" reverseOrder={false} />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  )
}
