services:
  mongodb:
    container_name: temu-kampus-mongodb
    image: mongo:8
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      temu-app-network:
        ipv4_address: 192.168.11.2
    command: [ "--replSet", "rs0", "--bind_ip", "localhost,temu-kampus-mongodb", "--(auth)", "--keyFile", "/etc/mongo-keyfile/mongodb-keyfile" ]
    volumes:
      - ./mongo_data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile/mongodb-keyfile

  app:
    container_name: temu-kampus-app
    build:
      context: ../
      dockerfile: ops/dev.Dockerfile
    # restart: always
    volumes:
      - ../:/app
    ports:
      - ${APP_PORT}:3000
    networks:
      temu-app-network:
        ipv4_address: 192.168.11.3
        
networks:
  temu-app-network:
    name: temu-app-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1
