services:
  app:
    container_name: temu-kampus-app
    build:
      context: ../
      dockerfile: ops/Dockerfile
    restart: always
    volumes:
      - ../:/var/www/apps
    ports:
      - ${APP_PORT}:3000
    networks:
      - temu-app-network

  mongodb:
    container_name: temu-kampus-mongodb
    image: mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - temu-app-network
    volumes:
      - ./mongo_data:/data/db

networks:
  temu-app-network:
    name: temu-app-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1
